app = "host-langflow-7vdqqq"
primary_region = "iad"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 7860
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 2
memory_mb = 4096

[mounts]
  source = "data"
  destination = "/var/lib/docker"


[build]
image = "langflowai/langflow:latest"
